### ISSUE TITLE
[Regression] Too few arguments to function field_ui_admin_access()

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#7045]
## Description of the bug

After updating from 1.32.0 to 1.33.x-dev and visiting the admin/reports/status page, site crashes with "Too few arguments to function field_ui_admin_access()"

## Steps To Reproduce

To reproduce the behavior, you need a site running 1.32.x to upgrade:

1. Log into the site as an admininstrator.
2. Replace the 1.32.x code with 1.33.x (e.g., via ftp or copying in locally).
3. Visit admin/reports/status. Crash happens. Reloading that page will still crash.

One can also reproduce it on a dev site with github access if you have `bee` working. Again, be logged in as an admin.

1. Check out 1.32.x.
2. `bee cc all` to clear all caches and reset things (mostly) to 1.32.x state.
3. Check out 1.33.x-dev.
4. Visit admin/reports/status. See crash. 
5. `bee cc` then `5` (menu) to clear the menu cache.
6. Reload admin/reports/status. Success.

## Expected behavior

No crash.

## Additional information

This is due to changes in [Add option to globally disable comments on a content type. · Issue #3016 · backdrop/backdrop-issues](https://github.com/backdrop/backdrop-issues/issues/3016). The problem seems to be that when `field_ui_admin_access` was changed to take 4 arguments, the menu cache still only passes 2 arguments until the menu cache is cleared.

More discussion at https://backdrop.zulipchat.com/#narrow/channel/218635-Backdrop/topic/Too.20few.20arguments.20to.20function.20field_ui_admin_access.28.29/with/566473064.

Even if the crash happens and no ordinary pages respond, running update.php clears the menu cache and fixes the problem.

**Comment by olafgrabienski** [comment]
I can confirm the issue. Happened to me when I updated a test site from 1.32.1 to [1.33.0-preview](https://github.com/backdrop/backdrop/releases/tag/1.33.0-preview), copying the files manually.

**Comment by quicksketch** [comment]
Thanks @herbdool. This seems like it should be manageable by making the two new arguments optional. For now that would result in the comment field tabs being temporarily inaccessible until update.php is run, but that is much better than a fatal error.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/5198 that should fix this.

As far as I could tell, just making the parameters nullable is sufficient to fix the problem. The logic within the function should handle just fine even if the parameters are excluded.

**Comment by quicksketch** [comment]
To test:

```
git checkout 1.32.x
ddev bee cc all # Or clear cache from admin bar
# Visit /admin/reports/status
git checkout 1.x
# Visit /admin/reports/status, without clearing cache
```

At this point, now the error is shown:

<img width="966" height="352" alt="Image" src="https://github.com/user-attachments/assets/f9b1373d-428c-4e54-9c45-3c39f8e1f99a" />

Switch to the PR branch without clearing caches and reload:

```
git checkout 7045--field_ui_admin_access-fix
# Visit /admin/reports/status, without clearing cache
```

Now without clearing caches, the `/admin/status/report` page does not error:

<img width="1188" height="174" alt="Image" src="https://github.com/user-attachments/assets/2558e36b-4239-4782-b5e2-b8dcff52def2" />

To my surprise, the comment field tabs are still accessible. Probably the same menu cache that caused the error also makes the previous access check continue to be used:

<img width="1188" height="174" alt="Image" src="https://github.com/user-attachments/assets/e018ba2e-b66a-4b2f-a83c-a02339e0a851" />

After clearing caches and the menu is rebuilt or running update.php, the comment tabs are removed properly.

<img width="1188" height="174" alt="Image" src="https://github.com/user-attachments/assets/8f8586b4-43c9-4175-9853-48a2fb21279e" />

**Comment by herbdool** [comment]
If this still might make it into 1.33 I'll try test tonight

**Comment by quicksketch** [comment]
Thanks @herbdool. I think delaying the release a few hours to have this fixed would be worthwhile.

**Comment by bugfolder** [comment]
I've tested this on a local site:

* Reverted to 1.32.0.
* `bee cc all`
* Checked out 1.33.x-dev.
* Visited the status report. Crash.
* Applied the diff from this PR.
* Rechecked the status report. No crash!

WFM. Code looks good (nice that it was such a simple fix!). LGTM.

**Comment by quicksketch** [comment]
Thanks @bugfolder! I've merged https://github.com/backdrop/backdrop/pull/5198 into 1.x for 1.33.0.
